[project]
name = "Infinite-Adventure"
version = "0.1.0"
description = "Infinite Adventure. Welcome."
authors = [{ name = "qingzhixing", email = "qzsqqmail@qq.com" }]
dependencies = []
requires-python = "==3.13.*"
readme = "README.md"
license = { text = "MIT" }

[tool.pdm]
distribution = false

[tool.pdm.scripts]
start = "python src/main.py"
release = "pyinstaller --distpath ./dist/dev --onefile --console src/main.py --name Infinite-Adventure"
clean = "cmd /c 'rmdir /s /q build dist 2>nul && del *.spec 2>nul || echo 清理完成'"

[dependency-groups]
dev = ["pyinstaller>=6.16.0"]
